apiVersion: v1
kind: Service
metadata:
  name: product-svc
spec:
  selector:
    app: product-svc
    tier: backend
  ports:
  - name: 8300-8300
    port: 8300
    protocol: TCP
    targetPort: 8300
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: 3306
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc
spec:
  selector:
    matchLabels:
      app: product-svc
      tier: backend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: product-svc
        tier: backend
        track: stable
    spec:
      containers:
      - image: shaksonik/product-svc:1.2.1
        name: product-svc
        ports:
        - name: svc-http-port
          containerPort: 8300
        - name: svc-db-port
          containerPort: 3306
        resources: {}
