apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-svc
spec:
  selector:
    matchLabels:
      app: product-svc
      tier: svc
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: product-svc
        tier: svc
        track: stable
    spec:
      containers:
      - image: shaksonik/product-svc:1.1
        name: product-svc
        resources: {}
status: {}
